image: 
  - Visual Studio 2017
  - Ubuntu
  
skip_tags: false

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version ($env:APPVEYOR_REPO_TAG_NAME).TrimStart("v")
      }

build_script:
  - dotnet build ./NVelocity.sln -c Release 

test_script:
  - dotnet test ./src/NVelocity.Tests --no-build -c Release

artifacts:
  - path: build/*.nupkg
    name: nvelocity
